GET https://7b57-211-244-225-211.ngrok-free.app/predict/and/left/0/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/and/left/0/right/1

GET https://7b57-211-244-225-211.ngrok-free.app/predict/and/left/1/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/and/left/1/right/1


GET https://7b57-211-244-225-211.ngrok-free.app/predict/or/left/0/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/or/left/0/right/1

GET https://7b57-211-244-225-211.ngrok-free.app/predict/or/left/1/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/or/left/1/right/1


GET https://7b57-211-244-225-211.ngrok-free.app/predict/nand/left/0/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nand/left/0/right/1

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nand/left/1/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nand/left/1/right/1


GET https://7b57-211-244-225-211.ngrok-free.app/predict/nor/left/0/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nor/left/0/right/1

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nor/left/1/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/nor/left/1/right/1


GET https://7b57-211-244-225-211.ngrok-free.app/predict/xor/left/0/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/xor/left/0/right/1

GET https://7b57-211-244-225-211.ngrok-free.app/predict/xor/left/1/right/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/xor/left/1/right/1


GET https://7b57-211-244-225-211.ngrok-free.app/predict/not/0

GET https://7b57-211-244-225-211.ngrok-free.app/predict/not/1


GET https://7b57-211-244-225-211.ngrok-free.app/train/and

GET https://7b57-211-244-225-211.ngrok-free.app/train/or

GET https://7b57-211-244-225-211.ngrok-free.app/train/not”

GET https://7b57-211-244-225-211.ngrok-free.app/train/nand

GET https://7b57-211-244-225-211.ngrok-free.app/train/nor

GET https://7b57-211-244-225-211.ngrok-free.app/train/xor